### ISSUE TITLE
Can't compile due some miss declarations.

### ISSUE THREAD

**Issue by Malkverbena** [GameNetworking/network_synchronizer#107]
Can't compile because some declarations don't match.

The functions SceneSynchronizerBase::set_frame_confirmation_timespan 
 and SceneSynchronizerBase::set_objects_relevancy_update_time should recive a float according to scene_synchronizer.h but in 
scene_synchronizer.cpp it recives a real_t.
The function SceneSynchronizerBase::get_objects_relevancy_update_time acording with the declaration on  scene_synchronizer.h should return a float  but on scene_synchronizer.cpp it returns a real_t.

Maybe it's missing a typedef or #define somewhere.

**Comment by Malkverbena** [comment]
SO: ubuntu 22.04
Compiller: CLANG

 modules/network_synchronizer/scene_synchronizer.cpp:256:6: error: no declaration matches 'void NS::SceneSynchronizerBase::set_frame_confirmation_timespan(real_t)'
  256 | void SceneSynchronizerBase::set_frame_confirmation_timespan(real_t p_interval) {
      |      ^~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:300:14: note: candidate is: 'void NS::SceneSynchronizerBase::set_frame_confirmation_timespan(float)'
  300 |         void set_frame_confirmation_timespan(float p_interval);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:114:7: note: 'class NS::SceneSynchronizerBase' defined here
  114 | class SceneSynchronizerBase {
      |       ^~~~~~~~~~~~~~~~~~~~~
modules/network_synchronizer/scene_synchronizer.cpp:272:6: error: no declaration matches 'void NS::SceneSynchronizerBase::set_objects_relevancy_update_time(real_t)'
  272 | void SceneSynchronizerBase::set_objects_relevancy_update_time(real_t p_time) {
      |      ^~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:306:14: note: candidate is: 'void NS::SceneSynchronizerBase::set_objects_relevancy_update_time(float)'
  306 |         void set_objects_relevancy_update_time(float p_time);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:114:7: note: 'class NS::SceneSynchronizerBase' defined here
  114 | class SceneSynchronizerBase {
      |       ^~~~~~~~~~~~~~~~~~~~~
modules/network_synchronizer/scene_synchronizer.cpp:276:8: error: no declaration matches 'real_t NS::SceneSynchronizerBase::get_objects_relevancy_update_time() const'
  276 | real_t SceneSynchronizerBase::get_objects_relevancy_update_time() const {
      |        ^~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:307:15: note: candidate is: 'float NS::SceneSynchronizerBase::get_objects_relevancy_update_time() const'
  307 |         float get_objects_relevancy_update_time() const;
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from modules/network_synchronizer/scene_synchronizer.cpp:2:
modules/network_synchronizer/scene_synchronizer.h:114:7: note: 'class NS::SceneSynchronizerBase' defined here
  114 | class SceneSynchronizerBase {

**Comment by AndreaCatania** [comment]
Hello, thanks for reporting this. Fixed here: https://github.com/GameNetworking/network_synchronizer/commit/65ba52d1bc2f6cd720d34fb0c20c98f74328e323
