### ISSUE TITLE
MultiplayerSynchronizer and 4.1

### ISSUE THREAD

**Issue by tapir** [GameNetworking/network_synchronizer#92]
Sorry to create an issue for a question but couldn't find any other place to reach out.
I've been looking for a solution for my multiplayer FPS game that has functionality for predicition & reconciliation. Looks like the project is dead on however what's not clear from the doc is 

- is it compatible with 4.1 or upcoming 4.2
- is it a complete replacement for MultiplayerSyncronizer and MultiplayerSpawner nodes or is it supposed to be complimentary
- apart from the example project are there any documents? is this an addon/extension? does it need to be compiled, how to start using etc?

thank you

**Comment by AndreaCatania** [comment]
Hello, no problem for opening an issue and I'm sorry that I'm replaying only now. I don't receive any notification when someone opens a PR or an issue on this repository, and I'm unable to figure out why.

Anyway, regarding your questions:

> I've been looking for a solution for my multiplayer FPS game that has functionality for predicition & reconciliation.

This is exactly what you are looking for.

> ... Looks like the project is dead on however ...

This project is not dead and is currently in development and maintained. Said that, there is no doc right now, but I plan to add it soon.

> is it compatible with 4.1 or upcoming 4.2

Yes it is.

> is it a complete replacement for MultiplayerSyncronizer and MultiplayerSpawner nodes or is it supposed to be complimentary

It's supposed to be complementary to `MultiplayerSpawner` and a replacement for `MultiplayerSyncronizer`.

> apart from the example project are there any documents?

The only documentation you can find is inside the C++ classes. I'm planning to write some docs soon.

> is this an addon/extension?

This is a module and not a extension. Maybe in future this will became an extension, but not yet.

> does it need to be compiled, how to start using etc?

You should be able to compile this module just by copying (or cloning using a submodule) this project into the godot modules directory.

----

Ask any other question here https://github.com/GameNetworking/network_synchronizer/discussions/categories/general I'll take care to answer there. In this way we can keep the issue section clear and each question on its own page.
